spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/spring_ssm
  mail:
    host: Smtp.163.com
    username: longzl202109@163.com
    password: ULINPTCHLMOMXICE
    port: 25
    default-encoding: UTF-8
    properties.mail.ssl.enable: true
server:
  port: 8080
