spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/spring_ssm
  mail:
    host: Smtp.163.com
#    TODO 记得添加密码和你的邮箱
    username: NULL
    password: NULL
    port: 25
    default-encoding: UTF-8
    properties.mail.ssl.enable: true
server:
  port: 8080
